[
    {"lib/identities/users.ex", :no_return},
    {"lib/identities/users.ex", :unknown_type},
    {"lib/identities/client_applications.ex", :no_return},
    {"lib/identities/client_applications.ex", :unknown_type},
    {"lib/identities/schemas/user.ex", :no_return},
    {"lib/identities/schemas/user.ex", :unknown_type},
    {"lib/identities/schemas/client_application.ex", :no_return},
    {"lib/identities/schemas/client_application.ex", :unknown_type},
    {"lib/identities/commands/create_user.ex", :unknown_type},
    {"lib/identities/commands/create_client_application.ex", :unknown_type},
    {"lib/identities/commands/get_identity.ex", :unknown_type},
    {"lib/credentials/passwords.ex", :no_return},
    {"lib/credentials/passwords.ex", :unknown_type},
    {"lib/credentials/public_keys.ex", :no_return},
    {"lib/credentials/public_keys.ex", :unknown_type},
    {"lib/credentials/schemas/password.ex", :no_return},
    {"lib/credentials/schemas/password.ex", :unknown_type},
    {"lib/credentials/schemas/public_key.ex", :no_return},
    {"lib/credentials/schemas/public_key.ex", :unknown_type},
    {"lib/credentials/passwords.ex", :unknown_type},
    {"lib/permissions/scopes.ex", :no_return},
    {"lib/permissions/scopes.ex", :unknown_type},
    {"lib/permissions/schemas/scope.ex", :no_return},
    {"lib/permissions/schemas/scope.ex", :unknown_type},
    {"lib/permissions/schemas/user_scope.ex", :no_return},
    {"lib/permissions/schemas/user_scope.ex", :unknown_type},
    {"lib/permissions/schemas/client_application_scope.ex", :no_return},
    {"lib/permissions/schemas/client_application_scope.ex", :unknown_type},
    {"lib/permissions/commands/consent_scope.ex", :unknown_type},
    {"lib/permissions/commands/remove_scope.ex", :unknown_type},
    {"lib/phoenix/router.ex", :pattern_match, 402}
]
