name: Elixir CI

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
        
    - name: Run Hex
      run: mix local.hex --force

    - name: Run Rebar
      run: mix local.rebar --force

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile code
      run: mix compile --warnings-as-errors
      
    - name: Ensure format
      run: mix format --check-formatted

    - name: Ensure code consistence
      run: mix credo --strict

    - name: Restore dialyzer cache
      uses: actions/cache@v3
      with:
        path: _build/
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Run static analysis
      run: mix dialyzer --no-check --halt-exit-status

    - name: Run tests
      run: mix coveralls.github
